# Generated by Django 5.2.4 on 2025-07-15 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0002_auto_20201101_2359"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="course",
            options={"verbose_name": "Курс", "verbose_name_plural": "Курсы"},
        ),
        migrations.AlterModelOptions(
            name="student",
            options={"verbose_name": "Студент", "verbose_name_plural": "Студенты"},
        ),
        migrations.AlterField(
            model_name="course",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="name",
            field=models.TextField(verbose_name="Наименование"),
        ),
        migrations.AlterField(
            model_name="course",
            name="students",
            field=models.ManyToManyField(
                blank=True, to="students.student", verbose_name="Студенты на курсе"
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="birth_date",
            field=models.DateField(null=True, verbose_name="Дата рождения"),
        ),
        migrations.AlterField(
            model_name="student",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="name",
            field=models.TextField(verbose_name="Имя"),
        ),
    ]
